version: '3.8'
services:
  lambda-hono-db:
    image: postgres:16
    platform: linux/amd64
    container_name: 'lambda-hono-db'
    env_file:
      - ../.env
    environment:
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      POSTGRES_DB: lambda_hono
    volumes:
      - ./postgresql_devmode:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5434:5432'
